export enum RideStatus {
  CREATED = "CREATED",
  CONFIRMED = "CONFIRMED",
  DRIVER_ASSIGNED = "DRIVER_ASSIGNED",
  STARTED = "STARTED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  FAILED = "FAILED",
}
